<?php

namespace WConvert\Privacy;

defined('ABSPATH') || exit;

/**
 * The privacy-policy text WConvert suggests to the merchant.
 *
 * WordPress collects these into the policy-editor's guide, where a merchant
 * copies what applies to their site. WSMS's `PrivacyServiceProvider` is the
 * pattern (ADR 0018).
 *
 * Two of the sentences are decisions rather than boilerplate:
 *
 * **The retention period is stated.** A merchant who configures one gets the
 * disclosure written for them, rather than discovering later that they needed
 * to write it. With none configured — which is how WConvert ships — it says
 * Leads are kept until deleted, because that is what happens.
 *
 * **Exported files are the merchant's to control.** A CSV already downloaded
 * is out of WConvert's reach permanently. Tracking exports so that it would
 * not be means logging who exported what, which is more personal data to solve
 * a personal-data problem — so the honest move is to say where the
 * responsibility went (ADR 0018).
 *
 * The dynamic facts come from {@see DataMap}, the same source the WConvert
 * admin reads. WordPress deliberately treats this as suggested text: changing
 * a Destination can flag the guide for review, but WConvert never edits the
 * site's published policy.
 *
 * @since 0.1.0
 */
final class PolicyText
{
    public function __construct(
        private readonly DataMap $map,
    ) {
    }

    public function register(): void
    {
        wp_add_privacy_policy_content('WConvert', $this->content());
    }

    /**
     * The suggestion, as the paragraphs WordPress renders into the guide.
     */
    public function content(): string
    {
        $summary = $this->map->summary();
        $paragraphs = [
            __('When you submit a form displayed by WConvert, we store what you entered — which may include your email address, phone number, name, selections and messages — along with the campaign and the date. WConvert does not attach the page address, IP address or browser details to that submission.', 'wconvert'),
            __('Where a form asked you to agree to something, we also store the wording of that agreement exactly as it was shown to you at the time, so that what you consented to can be established later.', 'wconvert'),
            $this->retentionSentence($summary['retention_days']),
        ];

        $destinationTypes = array_values(array_unique(array_map(
            static fn (array $destination): string => $destination['type_label'],
            $summary['destinations']
        )));

        if ($destinationTypes !== []) {
            $paragraphs[] = sprintf(
                /* translators: %s: comma-separated names of configured services, such as MailPoet and WP SMS contacts. */
                __('Depending on the form, submitted data may also be copied to these configured destinations: %s. Copies there are controlled by the site owner and the destination service, and may remain after WConvert’s copy is deleted.', 'wconvert'),
                implode(', ', array_map('esc_html', $destinationTypes))
            );
        }

        $paragraphs[] = __('When you interact with a WConvert campaign, the browser stores display, dismissal, conversion and optional A/B assignment state in local storage, with a cookie fallback. This state contains no contact details and no visitor identifier generated by WConvert.', 'wconvert');
        $paragraphs[] = sprintf(
            /* translators: %s: the short lifetime of an anonymous analytics rate-limit record. */
            __('To protect the anonymous campaign-counting endpoint, WConvert keeps a site-specific one-way hash derived from the network address for %s. The network address itself is not stored.', 'wconvert'),
            sprintf(
                /* translators: %s: a number of seconds. */
                _n('%s second', '%s seconds', $summary['beacon_rate_limit_seconds'], 'wconvert'),
                number_format_i18n($summary['beacon_rate_limit_seconds'])
            )
        );
        $paragraphs[] = __('Site administrators can export these submissions to a spreadsheet file. Once a file has been exported it is held by the site owner, and this plugin can no longer reach it.', 'wconvert');
        $paragraphs[] = __('You may ask the site owner for a copy of your retained WConvert submissions or for their deletion. Copies already sent to another service, exported, logged by email software or retained in backups must be handled separately.', 'wconvert');

        return '<p>' . implode('</p>' . "\n" . '<p>', $paragraphs) . '</p>';
    }

    /**
     * The one sentence the configured period changes.
     */
    private function retentionSentence(?int $days): string
    {
        if ($days === null) {
            return __('We keep these submissions until you delete them.', 'wconvert');
        }

        return sprintf(
            /* translators: %s: the configured retention period, already pluralised — "1 day", "90 days". */
            __('We keep these submissions for %s, after which they are deleted automatically.', 'wconvert'),
            sprintf(
                /* translators: %s: a number of days. */
                _n('%s day', '%s days', $days, 'wconvert'),
                number_format_i18n($days)
            )
        );
    }
}
