<?php
/** Read-only walkthrough hub on the guarded disposable site. */
add_action('template_redirect', static function (): void {
    if (!isset($_GET['library-scenarios'])) return;
    if (!current_user_can('manage_options')) { auth_redirect(); exit; }
    $plan = json_decode(file_get_contents(__DIR__ . '/../scenarios.json'), true, 512, JSON_THROW_ON_ERROR);
    $campaigns = get_option('wconvert_demo_campaigns', []);
    header('Content-Type: text/html; charset=utf-8');
    ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Business walkthroughs · WConvert</title><style>
    :root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#f6f5f0;color:#26372e;font:16px/1.65 system-ui,sans-serif}main{max-width:1100px;padding:48px 24px;margin:auto}h1{font:clamp(36px,5vw,58px)/1.1 Georgia,serif;letter-spacing:-.035em;max-width:750px}h2{font:28px/1.2 Georgia,serif}h3{font-size:14px;margin-top:24px}p{max-width:760px}.intro{color:#5b6a60}article{background:#fff;border:1px solid #d8dfd6;border-radius:16px;margin:28px 0;padding:28px}.links{display:flex;flex-wrap:wrap;gap:10px}a{color:#315d49}a:focus-visible{outline:3px solid #a6512b;outline-offset:4px}.links a{display:inline-flex;align-items:center;min-height:44px;padding:9px 14px;border:1px solid #cbd7cc;border-radius:7px;font-size:14px;text-decoration:none}li{padding:5px 0}.scope{border-left:3px solid #56715c;padding-left:18px;font-size:14px}.eyebrow{font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:#526759}@media(max-width:500px){main{padding:28px 16px}article{padding:20px}.links a{width:100%}ol{padding-left:22px}}
    </style></head><body><main><a href="<?php echo esc_url(home_url('/?library-demo=1')); ?>">← All campaign demos</a><p class="eyebrow">Practical template review</p><h1>Three businesses.<br>Complete visitor journeys.</h1><p class="intro"><?php echo esc_html($plan['scope']); ?></p><p class="scope">Use fictional details. Every campaign opens on its own page to keep its trigger and capture evidence clear. All steps below require a reviewer; the presence of a checklist is not a pass.</p>
    <?php foreach ($plan['scenarios'] as $scenario): ?><article id="<?php echo esc_attr($scenario['id']); ?>"><p class="eyebrow"><?php echo esc_html($scenario['id']); ?></p><h2><?php echo esc_html($scenario['name']); ?></h2><p><?php echo esc_html($scenario['need']); ?></p><div class="links"><?php foreach ($scenario['campaigns'] as $id): if (!isset($campaigns[$id])) { echo '<p>Demo not seeded: ' . esc_html($id) . '</p>'; continue; } $entry = $campaigns[$id]; ?><a href="<?php echo esc_url(get_permalink($entry['page'])); ?>"><?php echo esc_html($entry['name'] . ' · ' . str_replace('_', ' ', $entry['type'])); ?></a><?php endforeach; ?></div><h3>Walk through the whole task</h3><ol><?php foreach ($scenario['steps'] as $step): ?><li><?php echo esc_html($step); ?></li><?php endforeach; ?></ol><h3>What a useful outcome looks like</h3><p><?php echo esc_html($scenario['success']); ?></p></article><?php endforeach; ?>
    <p class="scope">External email/SMS delivery is skipped. Physical-device checks and real merchant conversion measurements remain separate from these local walkthroughs.</p></main></body></html><?php
    exit;
});
