import { render, screen, within, fireEvent, cleanup } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import type { TemplateTree } from '@renderer/types';
import { CampaignScreenNavigator } from '../../resources/admin/src/builder/CampaignScreenNavigator';
import fixture from '../fixtures/journey-graph-branch-groups.json';
const tree = fixture as unknown as TemplateTree;
afterEach(cleanup);
it('keeps each interest group under its source, renders every screen once, and selects the actual child', () => {
  const select = vi.fn();
  const at = tree.steps.findIndex(item => item.id === 'home_garden');
  render(<CampaignScreenNavigator tree={tree} step={at} onSelect={select} onFlow={() => {}} />);
  const home = screen.getByRole('region', { name: 'Follow-ups: Your home interests' });
  const business = screen.getByRole('region', { name: 'Follow-ups: Your business interests' });
  expect(home.parentElement).toHaveTextContent('Your home interests');
  expect(home.parentElement).not.toHaveTextContent('Your business interests');
  expect(within(home).getByText('If “Garden landscaping” is selected')).toBeInTheDocument();
  expect(within(business).queryByText('Garden landscaping details')).toBeNull();
  for (const item of tree.steps) expect(screen.getAllByText(item.name, { exact: true })).toHaveLength(1);
  const button = within(home).getByRole('button', { name: /Garden landscaping details/ });
  expect(button).toHaveAttribute('aria-current', 'true');
  fireEvent.click(button);
  expect(select).toHaveBeenCalledWith(at);
});
