import { beforeEach, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import apiFetch from '@wordpress/api-fetch';
import { SpamProtection } from '../../resources/admin/src/settings-page/SpamProtection';
import { verify } from '../../resources/loader/src/protection';
vi.mock('@wordpress/api-fetch', () => ({ default: vi.fn() }));
vi.mock('../../resources/loader/src/protection', () => ({ verify: vi.fn() }));
const saved = { site_hostname: 'example.test', provider: 'none', site_key: '', has_secret: false, rules_available: false, rules_configured: false, rule_fields: [], diagnostics: { since: 1, counts: {} } };
beforeEach(() => { vi.mocked(verify).mockReset(); vi.mocked(apiFetch).mockReset(); vi.mocked(apiFetch).mockResolvedValue(saved); });
it('offers all three providers without a Pro gate and preserves drafts after failed saves', async () => {
  render(<SpamProtection />);
  fireEvent.change(await screen.findByLabelText('Bot verification'), { target: { value: 'turnstile' } });
  expect(screen.getByRole('option', { name: 'Google reCAPTCHA v2 checkbox' })).toBeInTheDocument();
  expect(screen.getByRole('option', { name: 'hCaptcha' })).toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Site key'), { target: { value: 'site' } });
  fireEvent.change(screen.getByLabelText('Secret key'), { target: { value: 'secret' } });
  vi.mocked(apiFetch).mockRejectedValueOnce({ message: 'Keys are invalid' });
  fireEvent.click(screen.getByRole('button', { name: 'Save protection' }));
  await screen.findByText('Keys are invalid');
  expect(screen.getByLabelText('Site key')).toHaveValue('site'); expect(screen.getByLabelText('Secret key')).toHaveValue('secret');
});
it('distinguishes testing from saving and clears successful verification when keys change', async () => {
  vi.mocked(apiFetch).mockResolvedValue({ ...saved, provider: 'turnstile', site_key: 'site', has_secret: true });
  let complete!: (token: string) => void;
  vi.mocked(verify).mockImplementation(() => new Promise(resolve => { complete = resolve; }));
  render(<SpamProtection />);
  fireEvent.click(await screen.findByRole('button', { name: 'Test saved setup' }));
  expect(screen.getByRole('button', { name: 'Testing…' })).toBeDisabled();
  expect(screen.getByRole('button', { name: 'Save protection' })).toBeDisabled();
  await waitFor(() => expect(verify).toHaveBeenCalledOnce());
  complete('verified-token');
  await screen.findByText('Test passed. No lead created or messages sent.');
  await waitFor(() => expect(screen.getByRole('button', { name: 'Test saved setup' })).toHaveFocus());
  expect(apiFetch).toHaveBeenLastCalledWith({ path: '/wconvert/v1/protection/test', method: 'POST', data: { verification_token: 'verified-token' } });
  fireEvent.change(screen.getByLabelText('Site key'), { target: { value: 'edited-key' } });
  expect(screen.queryByText('Test passed. No lead created or messages sent.')).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'Test saved setup' })).toBeDisabled();
});
it('gives a useful retry message and restores focus when the setup challenge cannot load', async () => {
  vi.mocked(apiFetch).mockResolvedValue({ ...saved, provider: 'turnstile', site_key: 'site', has_secret: true });
  vi.mocked(verify).mockRejectedValue(undefined);
  render(<SpamProtection />);
  fireEvent.click(await screen.findByRole('button', { name: 'Test saved setup' }));
  await screen.findByText('Test failed. Check your saved keys and hostname, then retry.');
  await waitFor(() => expect(screen.getByRole('button', { name: 'Test saved setup' })).toHaveFocus());
  expect(apiFetch).toHaveBeenCalledTimes(2);
  expect(screen.getByText('example.test')).toBeInTheDocument();
});
it('sends an empty secret to retain an existing key and clears it from the UI after saving', async () => {
  vi.mocked(apiFetch).mockResolvedValue({ ...saved, provider: 'turnstile', site_key: 'site', has_secret: true });
  render(<SpamProtection />);
  expect(await screen.findByLabelText('Secret key')).toHaveValue('');
  fireEvent.change(screen.getByLabelText('Site key'), { target: { value: 'new-site' } });
  fireEvent.click(screen.getByRole('button', { name: 'Save protection' }));
  await waitFor(() => expect(apiFetch).toHaveBeenLastCalledWith({ path: '/wconvert/v1/protection', method: 'POST', data: { provider: 'turnstile', site_key: 'new-site', secret: '' } }));
  await screen.findByText('Settings saved.');
});
